### ISSUE TITLE
how on earth do i get rid of this?

### ISSUE THREAD

**Issue by segaegaf** [PFE1718/PFE1718-automation-handler#1]
So not sure why but this isn't installed on my mycroft
yet every 5min or so mycroft whines about this skill missing 2 other skills and asks if i want to install
i try to uninstall this skill however it is stated as not being installed

i also attempted to reply "yes" but nope don't work

**Comment by segaegaf** [comment]
am legit about to uninstall mycroft due to this shit.
Every 5min it whines 

https://i.imgur.com/GHAUliQ.png

**Comment by RReivax** [comment]
Just delete all related skills  in /opt/mycroft/skills folder.
Be sure you don't have "habit-miner", "skill-listener" or "automation-handler" there.

**Comment by segaegaf** [comment]
thanks for the quick reply. 
Finally it is done whining about this ^^
